default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  user: postgres
  password: postgres
  pool: 5
development:
  <<: *default
  database: sample_app_development

test:
  <<: *default
  database: sample_app_test